### ISSUE TITLE
Baseline

### ISSUE THREAD

**Issue by RolandTi** [pluxml/PluCSS#10]
Salut ! 
PluCSS utilise t'il une grille horizontale comme cet exemple : http://matejlatin.github.io/Gutenberg/ ?
merci d'avance !

**Comment by P3ter** [comment]
Bonjour,

Je réponds très tardivement, désolé.

PluCSS n'implémente pas de "grille horizontale" tel quel l'entend le projet _Gutenberg_. En revanche certains élements de typographies sont redéfinis de manière statique (voir _body_, _h1_, _h2_, ...) via des règles _line-height_ et _font-size_, pour apporter une cohérence globale. Il n'est pas possible de redéfinir ces éléments de manière centralisée comme le propose _Gutenberg_.

Cependant, je note l'idée pour une futur version de PluCSS.
